[build]
  command = "bun run build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Use Bun on Netlify build image
  BUN_VERSION = "1.1.21"
  # Set NODE_ENV to production to avoid Html import errors
  NODE_ENV = "production"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Service-Secret"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
